### ISSUE TITLE
Data too long for column 'data'

### ISSUE THREAD

**Issue by ystepanoff** [ystepanoff/updaemon#10]
```
[2023-01-23 11:31:02,247] DEBUG - https://shop.flipperzero.one:443 "GET / HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/opt/updaemon/app/main.py", line 104, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/updaemon/app/main.py", line 96, in main
    await asyncio.gather(*tasks)
  File "/opt/updaemon/app/main.py", line 56, in process_source
    await db_handler.upsert_state(source_id, new_state)
  File "/opt/updaemon/app/utils/db_handler.py", line 103, in upsert_state
    await cur.execute("""
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 672, in _read_query_result
    await result.read()
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 1153, in read
    first_packet = await self.connection._read_packet()
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 641, in _read_packet
    packet.raise_for_error()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'data' at row 1")
```

Changing `data` type from `TEXT` to `LONGTEXT` on the box resulted in

```
[2023-01-23 11:38:01,829] DEBUG - https://shop.flipperzero.one:443 "GET / HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/opt/updaemon/app/main.py", line 104, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/updaemon/app/main.py", line 96, in main
    await asyncio.gather(*tasks)
  File "/opt/updaemon/app/main.py", line 56, in process_source
    await db_handler.upsert_state(source_id, new_state)
  File "/opt/updaemon/app/utils/db_handler.py", line 103, in upsert_state
    await cur.execute("""
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 672, in _read_query_result
    await result.read()
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 1153, in read
    first_packet = await self.connection._read_packet()
  File "/opt/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 641, in _read_packet
    packet.raise_for_error()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1366, 'Incorrect string value: \'\\xE2\\x9C\\x93" /...\' for column \'data\' at row 1')
```
MySQL's `utf8` only permits characters that can be encoded by 3 bytes; here we have characters that need 4 bytes.
The following migration is needed to resolve the issue (hotfixed on the box):
```
ALTER TABLE state MODIFY COLUMN data LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

One to meditate on: should the MySQL settings be changed to 
```
 [mysql]
 default-character-set=utf8mb4

 [mysqld]
 character-set-server=utf8mb4
 collation-server=utf8mb4_unicode_ci
```
instead?

**Comment by ystepanoff** [comment]
UPD: probably worth just storing a hash value as an MVP.
